#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
INPUT_FILE="${REPO_ROOT}/variables.hcl"
OUTPUT_FILE="${1:-${REPO_ROOT}/docs/variables.md}"

python3 - "$INPUT_FILE" "$OUTPUT_FILE" <<'PY'
import pathlib
import re
import sys

input_path = pathlib.Path(sys.argv[1])
output_path = pathlib.Path(sys.argv[2])
content = input_path.read_text(encoding="utf-8")

block_pattern = re.compile(r'^variable\s+"([^"]+)"\s*\{\n(.*?)^\}', re.MULTILINE | re.DOTALL)

def normalize_default(raw: str) -> str:
    value = raw.strip()
    if "\n" in value:
        value = " ".join(line.strip() for line in value.splitlines() if line.strip())
        value = re.sub(r"\s+", " ", value)
    return value

def escape_cell(value: str) -> str:
    return value.replace("|", "\\|")

variables = []
for match in block_pattern.finditer(content):
    name, block = match.groups()

    type_match = re.search(r'^\s*type\s*=\s*(.+)$', block, re.MULTILINE)
    desc_match = re.search(r'^\s*description\s*=\s*"(.*)"\s*$', block, re.MULTILINE)
    default_match = re.search(r'^\s*default\s*=\s*(.+)$', block, re.MULTILINE | re.DOTALL)

    var_type = type_match.group(1).strip() if type_match else ""
    description = desc_match.group(1).strip() if desc_match else ""
    default = normalize_default(default_match.group(1)) if default_match else ""

    variables.append({
        "name": name,
        "type": var_type,
        "default": default,
        "description": description,
    })

lines = [
    "# Variable Reference",
    "",
    "> **Auto-generated:** `scripts/generate-vars-doc.sh` from `variables.hcl`.",
    "> Do not edit this file manually.",
    "",
    "| Variable | Type | Default | Description |",
    "| --- | --- | --- | --- |",
]

for var in variables:
    lines.append(
        "| `{name}` | `{type}` | `{default}` | {description} |".format(
            name=escape_cell(var["name"]),
            type=escape_cell(var["type"]),
            default=escape_cell(var["default"]),
            description=escape_cell(var["description"]),
        )
    )

output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY
