#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
INPUT_FILE="${REPO_ROOT}/variables.hcl"
OUTPUT_FILE="${1:-${REPO_ROOT}/docs/variables.md}"

python3 - "$INPUT_FILE" "$OUTPUT_FILE" <<'PY'
import pathlib
import re
import sys

input_path = pathlib.Path(sys.argv[1])
output_path = pathlib.Path(sys.argv[2])
content = input_path.read_text(encoding="utf-8")

block_pattern = re.compile(r'^variable\s+"([^"]+)"\s*\{\n(.*?)^\}', re.MULTILINE | re.DOTALL)

def normalize_default(raw: str) -> str:
    value = raw.strip()
    if "\n" in value:
        value = " ".join(line.strip() for line in value.splitlines() if line.strip())
        value = re.sub(r"\s+", " ", value)
    return value

def escape_cell(value: str) -> str:
    return value.replace("|", "\\|")

def extract_default(block: str) -> str:
    match = re.search(r'^\s*default\s*=\s*(.*)$', block, re.MULTILINE)
    if not match:
        return ""

    first_line_value = match.group(1).rstrip()
    if not first_line_value:
        return ""

    remaining_block = block[match.end():]
    source = first_line_value
    if remaining_block:
        source += "\n" + remaining_block

    opening_to_closing = {"[": "]", "{": "}", "(": ")"}
    first_non_whitespace = next((ch for ch in first_line_value.lstrip()[:1]), "")
    if first_non_whitespace not in opening_to_closing:
        return first_line_value.strip()

    expected_closing = opening_to_closing[first_non_whitespace]
    depth = 0
    in_string = False
    escaped = False

    for index, ch in enumerate(source):
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue

        if ch == '"':
            in_string = True
            continue

        if ch == first_non_whitespace:
            depth += 1
        elif ch == expected_closing:
            depth -= 1
            if depth == 0:
                return source[: index + 1].strip()

    return first_line_value.strip()

variables = []
for match in block_pattern.finditer(content):
    name, block = match.groups()

    type_match = re.search(r'^\s*type\s*=\s*(.+)$', block, re.MULTILINE)
    desc_match = re.search(r'^\s*description\s*=\s*"(.*)"\s*$', block, re.MULTILINE)

    var_type = type_match.group(1).strip() if type_match else ""
    description = desc_match.group(1).strip() if desc_match else ""
    default = normalize_default(extract_default(block))

    variables.append({
        "name": name,
        "type": var_type,
        "default": default,
        "description": description,
    })

lines = [
    "# Variable Reference",
    "",
    "> **Auto-generated:** `scripts/generate-vars-doc.sh` from `variables.hcl`.",
    "> Do not edit this file manually.",
    "",
    "| Variable | Type | Default | Description |",
    "| --- | --- | --- | --- |",
]

for var in variables:
    lines.append(
        "| `{name}` | `{type}` | `{default}` | {description} |".format(
            name=escape_cell(var["name"]),
            type=escape_cell(var["type"]),
            default=escape_cell(var["default"]),
            description=escape_cell(var["description"]),
        )
    )

priority_section = """
## Job Priority

Nomad uses an integer priority on the **1–100 scale** (higher = more important).  The
two priority variables must always satisfy `web_priority > worker_priority` so that
the web UI is scheduled preferentially over calculation workers whenever the cluster
is under resource pressure.

| Variable | Default | Kubernetes equivalent | K8s value |
| --- | --- | --- | --- |
| `web_priority` | `80` | `high-priority` PriorityClass | `1000000` |
| `worker_priority` | `40` | `low-priority` PriorityClass | `10000` |

### How the mapping works

The Helm chart creates two Kubernetes `PriorityClass` objects:

- **`high-priority`** (value `1000000`) – assigned to the web-UI `Deployment`
- **`low-priority`** (value `10000`) – assigned to worker `Deployments`

The ratio between those values is large (100×) but what Kubernetes cares about is the
relative ordering, not the absolute numbers.  Nomad's priority scale is 1–100 and
achieves the same relative ordering with `web_priority = 80` (high) vs
`worker_priority = 40` (low).

> **Warning:** inverting the two values (setting `worker_priority` ≥ `web_priority`)
> will cause the scheduler to evict or delay the web UI in favour of workers during
> resource contention, degrading operator access to the running analysis.
"""

output_path.write_text("\n".join(lines) + "\n" + priority_section, encoding="utf-8")
PY
